name: 'Google Indexing'
description: 'Index your site on Google using the Indexing API.'
author: 'slucha'

inputs:
  siteUrl:
    description: 'The URL of the site to be indexed'
    required: true
    default: 'sc-domain:pomodorotimerapp.com'
  gcpServiceAccountKey:
    description: 'The GCP service account key in JSON format.'
    required: true

runs:
  using: node20
  main: dist/index.mjs

