name: Google Indexing

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:      # Allows manual triggering

jobs:
  google-indexing:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Inputs
        run: |
          echo "Site URL: pomodorotimerapp.com"
          echo "Service Account Key: [REDACTED]"

      - name: Run Google Indexing Action
        id: run-indexing
        uses: slucha/action-google-indexing@main
        with:
          siteUrl: 'pomodorotimerapp.com' # Pass only the domain here
          gcpServiceAccountKey: ${{ secrets.Google_Service_Account_Secret }}
        continue-on-error: true

      - name: Capture Error (if any)
        if: failure()
        run: |
          echo "The indexing action failed. Reviewing error details..."
          echo "${{ steps.run-indexing.outputs.error }}" || echo "No detailed error output captured."
